HOST: http://huntjs.herokuapp.com/

--- huntjs Api V1 ---



-- User authorization API via various Passport.js strategies --

--- Facebook ---


Authorization
GET /auth/facebook
< 302


Callback for authorization
GET /auth/facebook/callback
< 302
